name: US Government APIs
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: Gray Brooks
  url: https://pages.18f.gov/API-All-the-X/

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  internal: true
- text: 18F List
  url: 18f-list/
  internal: true
- text: API Listing on Data.gov
  url: datagov/
  internal: true
- text: 3rd-Party Catalogs
  url: other-lists/
  internal: true
- text: Short Term Fixes
  url: short-term-fixes/
  internal: true
- text: A Sustainable Model
  url: sustainable-model/
  internal: true
- text: How You Can Help
  url: https://github.com/unitedstates/APIs/labels/help%20wanted
  internal: false

repos:
- name: APIs
  description: Main repository
  url: https://github.com/unitedstates/APIs

# Style Variables
brand_color: "#1188ff"
